---
title: "Notes on The New Geography of Jobs"
author: "Tham, Wei Yang"
date: "2017-04-23"
output: html_document
tags:
  - notes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Usual disclaimer: this is just a collection of notes I made while reading Enrico Moretti's [*The New Geography of Jobs*](https://www.amazon.com/New-Geography-Jobs-Enrico-Moretti/dp/0544028058). It's not meant to be a review, summary, or endorsement. 

If you've taken a graduate class in labor or urban economics, much of this book will be familiar to you. There's still plenty to learn of course, and it's nice to see work from various areas being tied together for a big picture overview. 

- [Michelle Alexopoulos has a paper](http://homes.chass.utoronto.ca/~malex/readallaboutittechnology.pdf) that measures technology changes based on the appearance of new book titles in a field. She argues that book titles more accurately capture the timing of a technology shock than patents. 

- I didn't know that Bill Gates and Paul Allen moved Microsoft from New Mexico to Seattle because they wanted to go home (although the [Microsoft wiki entry](https://en.m.wikipedia.org/wiki/History_of_Microsoft) says the move was because it was hard to recruit programmers to Albuquerque.)

- "Cricket spills over into business" - I like this quote on the role of face-to-face interactions in innovation 

- The concept of "cowork" - essentially the idea is to gather all sorts of creative types (entrepreneuers, designers etc.) in the same area, and they can work on their own projects but now have the option of bouncing ideas off of people from other domains. Apparently Square came out of cowork. 
