---
title: "My first ever R package!"
author: "Tham, Wei Yang"
date: "2017-06-11"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.align = 'center', fig.width = 9)
```

Well this is pretty darn exciting. I made my first package and first custom theme! Check it out [here](https://github.com/weiyangtham/econothemes)!

You can install it as follows: 

```{r, eval = FALSE}
devtools::install_github("weiyangtham/econothemes")
```

Here's a quick example: 

```{r}
library(ggplot2)
library(econothemes)

ggplot(mtcars, aes(mpg, wt)) +
  geom_point() +
  labs(x="Fuel efficiency (mpg)", y="Weight (tons)",
       title="Seminal ggplot2 scatterplot example",
       subtitle="A plot that is only useful for demonstration purposes",
       caption="Same example as in hrbrthemes'") + 
  theme_nber()
```

I'll do a more in-depth post about the process, complete with acknowledgements for all the people whose Github accounts I raided for code, but for now I just really wanted to share this. 


