---
title: "Purpose of this blog"
author: "Tham, Wei Yang"
excerpt: "Outlining how I plan to use the blog"
date: "2017-01-17"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

I've experimented with blogging before, but after a while I wanted to find a way to integrate my blogging with R/RStudio, and would give me the flexibility to integrate data visualizations with text. Along the way, I also made a decision that I wanted to blog about a narrower range of topics, but hopefully more deeply. 

This decision was inspired by Ezra Klein's own blogging experience. Across a number of interviews, Ezra talks about how he used blogging as a learning tool. Blogging has the following benefits: it allows you to revisit the same topic over and over again, the act of writing itself helps you to process things you've learnt, and people are generally more forgiving of mistakes you make in a blog post, as opposed to say a newspaper article or research paper. 

As of this writing, much of my research is in the context of science and science policy, and I want to to use the blog as a way to deepen my knowledge in that area.

Of course, I reserve the right to adjust the scope of this blog in the future, but as of now I want to stick to the following topics:

- Economics of science and science policy, U.S. and International
- Econometrics and statistics
- Reproducibility and replicability
- Data visualization

It should be fun, and if you happen to be reading this, check out my other posts and [let me know what you think](https://twitter.com/wytham88)!



